---
GITHUB: http
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: https://github.com
GITORIOUS: http
GITORIOUS_ROOT: https://git.gitorious.org
GITORIOUS_PUSH_ROOT: https://git.gitorious.org
SPACEGIT: http
SPACEGIT_ROOT: https://git.hb.dfki.de
SPACEGIT_PUSH_ROOT: https://git.hb.dfki.de
DFKIGIT: http
DFKIGIT_ROOT: https://git.hb.dfki.de
DFKIGIT_PUSH_ROOT: https://git.hb.dfki.de
rtt_target: gnulinux
rtt_corba_implementation: omniorb
osdeps_mode: all
USE_OCL: false
WITH_PYTHON: true
AUTOBUILD_ARCHIVE_AUTOUPDATE: true
ccache: true
iceCC: true
iceCC_parallel: '15'
ROCK_SELECTED_FLAVOR: master
ROCK_BRANCH: master
ldgold: false
cxx11: true
DEB_USE: true
debian_release: master-20.06
DEB_AUTOMATIC: true
apt_dpkg_update: true
USE_PYTHON: true
pure_mars: false
python_executable: "/usr/bin/python3.8"
prefer_indep_over_os_packages: false
GITHUB_PRIVATE_ROOT: https://github.com
GITORIOUS_PRIVATE_ROOT: https://git.gitorious.org
SPACEGIT_PRIVATE_ROOT: https://git.hb.dfki.de
DFKIGIT_PRIVATE_ROOT: https://git.hb.dfki.de
ROCK_FLAVOR: master
typelib_cxx_loader: castxml
syskit_use_bundles: true
ccacheDir: default
ccacheSize: 10G
