---
set:
  AUTOPROJ_CURRENT_ROOT:
  - "/opt/workspace"
  ROCK_WEBAPP_CUSTOM_PATH:
  - "${AUTOPROJ_CURRENT_ROOT}/webapp/sherpa_tt/src/ui"
  GEM_HOME:
  - "/root/.local/share/autoproj/gems/ruby/2.7.0"
  BUNDLE_GEMFILE:
  - "/opt/workspace/install/gems/Gemfile"
  PYTHONUSERBASE:
  - "/opt/workspace/install/pip"
  LC_NUMERIC:
  - C
  LC_ALL:
  - en_US.UTF-8
  LANG:
  - en_US.UTF-8
  MCSLIB_PATH:
  - "/opt/workspace/sherpa_tt/sherpa_tt_mcs"
  OROCOS_TARGET:
  - gnulinux
  ROBY_PLUGIN_PATH:
  - "/opt/workspace/tools/syskit/lib/syskit/roby_app/register_plugin.rb"
  - "/opt/workspace/base/scripts/lib/rock/roby_plugin.rb"
  NODE_PATH:
  - "/opt/workspace/install/lib/node_modules"
  cat_metamodeling_DIR:
  - "/opt/workspace/install/share/cat-metamodeling/cmake"
  CAT_PLUGIN_PATH:
  - "/opt/workspace/install/share/cat-metamodeling/plugins"
  CAT_MODEL_PATH:
  - "/opt/workspace/install/share/cat-metamodeling/cats"
  ROCK_BUNDLE_PATH:
  - "/opt/workspace/bundles"
  - "/opt/workspace/install/share/rock"
  ROCK_BUNDLE:
  - "/opt/workspace/bundles/sherpa_tt_corobx"
  QT_PLUGIN_PATH:
  - "/opt/workspace/install/lib/qt"
  VIZKIT_PLUGIN_RUBY_PATH:
  - "/opt/workspace/install/lib"
  OSG_FILE_PATH:
  - "/opt/workspace/install/share/vizkit"
  TYPELIB_PLUGIN_PATH:
  - "/opt/workspace/install/lib/typelib"
  TYPELIB_CXX_LOADER:
  - castxml
  ROCK_WEBAPP:
  - "/opt/workspace/tools/rest_api/share/rest_api"
  ORBInitRef:
  - NameService=corbaname::127.0.0.1
  TYPELIB_RUBY_PLUGIN_PATH:
  - "/opt/workspace/install/share/typelib/ruby"
  OROGEN_PLUGIN_PATH:
  - "/opt/workspace/install/share/orogen/plugins"
  OROGEN_MODEL_PATH:
  - "/opt/workspace/install/share/orogen/models"
  ROCK_PREFIX:
  - "/opt/workspace/install/share/rock"
  SYSKIT_USE_ROCK_BUNDLES:
  - '1'
  Syskit_DIR:
  - "/opt/workspace/tools/syskit/cmake"
  RTT_COMPONENT_PATH:
  - "/opt/workspace/install/lib/orocos/plugins"
  ROCK_TEMPLATE_PREFIX:
  - "/opt/workspace/base/templates/"
  ROCK_TEMPLATE_SUFFIX:
  - ''
unset:
- GEM_PATH
- BUNDLER_VERSION